Add Pull Request Club
perl-foundation-outreach/gsoc-2021-ideas pull request #2
Opened 2021-01-31 12:35 UTC by kyzn

Hi! I was thinking Pull Request Club could be a nice project to add here. I added it in 2019, but it didn't get a chance back then. Let's try again?

Do let me know if this needs any clarification or updates. Thanks!

2021-01-31 16:30 UTC, JJ requested changes
Please check out my comments, and we're good to go.

2021-01-31 16:30 UTC, JJ commented on perl/PullRequestClub.md
> +
You should maybe move a few "expected outcomes" here as objectives. A project, to be picked up by a student, should have a clear objective or sets of objectives. If you've got a roadmap for the site, point at it; if there are a few milestones, that would help too.

2021-01-31 16:30 UTC, JJ commented on perl/PullRequestClub.md
> +Experience with Perl & SQL. Knowledge about web applications.
Please specify a bit more here. Client-server? Web services?  MVC?

2021-02-19 07:14 UTC, JJ commented
Do you want to give this a one-over before we close?

2021-02-19 08:36 UTC, kyzn commented
Hey JJ! Thanks for the reminder, and apologies for the wait. Let me spend some time on this on weekend, and update the branch.

2021-02-22 13:35 UTC, kyzn commented
Hey @JJ, thanks for waiting. I've updated the details, can you let me know if it looks good? Thanks!

2021-02-22 13:54 UTC, JJ approved these changes
Looks fine. Thanks!

2021-02-22 13:54 UTC, merged