Add project for improved Rakudo Star support
perl-foundation-outreach/gsoc-2021-ideas pull request #6
Opened 2021-02-01 16:43 UTC by Tyil

2021-02-01 16:52 UTC, JJ commented on raku/rakudo-star-support.md
> +
Please add here a few milestones the student would be expected to reach; one or two will be enough.

2021-02-01 16:53 UTC, JJ requested changes
Please clarify a few things and we're good.

2021-02-01 16:53 UTC, JJ commented on raku/rakudo-star-support.md
> +  - Windows
NetBSD? Is that still a thing?

2021-02-01 16:53 UTC, JJ commented on raku/rakudo-star-support.md
> +
You can also use perl in GitHub actions :-) So this would go _both_ ways.

2021-02-02 08:06 UTC, Tyil commented
On Mon, Feb 01, 2021 at 08:52:36AM -0800, Juan Julián Merelo Guervós wrote:
> Please add here a few milestones the student would be expected to reach; one or two will be enough.

I was thinking of making every platform a single milestone, but I'm not sure if
that's what you're thinking of too. If that works for you, I can clarify this
in the post if desired.

-- 
With kind regards,

Patrick Spek


www:  https://www.tyil.nl/
mail: p.spek@tyil.nl
pgp:  1660 F6A2 DFA7 5347 322A  4DC0 7A6A C285 E2D9 8827

social: https://soc.fglt.nl/tyil
git:    https://home.tyil.nl/git

2021-02-02 08:06 UTC, Tyil commented
On Mon, Feb 01, 2021 at 08:53:50AM -0800, Juan Julián Merelo Guervós wrote:
> Please clarify a few things and we're good.
> 
> [...]
> 
> NetBSD? Is that still a thing?

Yes it is, I'll include it in the list.

> You can also use perl in GitHub actions :-) So this would go _both_ ways.

Good to know!

-- 
With kind regards,

Patrick Spek


www:  https://www.tyil.nl/
mail: p.spek@tyil.nl
pgp:  1660 F6A2 DFA7 5347 322A  4DC0 7A6A C285 E2D9 8827

social: https://soc.fglt.nl/tyil
git:    https://home.tyil.nl/git

2021-02-02 10:54 UTC, merged